### ISSUE TITLE
Dongle Test and Dongle Dump not working

### ISSUE THREAD

**Issue by Ali-Mohebbi** [Xyl2k/DongleMe#2]
I built these two files but when I checked these two app with real Rockey4ND dongle It Saied dongle not fount but R4ND editor software can detect dongle.
also emulator only support your password and by changing the passwords in registry not happened. I thins the signature must be modified. if yes, please help me how I can generate signature.

**Comment by Xyl2k** [comment]
Is not for another dongle other than mine, for a piracy solution you will have to look elsewhere.

**Comment by Xyl2k** [comment]
I built these two files but when I checked these two app with real Rockey4ND dongle It Saied dongle not fount // wich app are you talking about?

**Comment by Ali-Mohebbi** [comment]
I mean 2 application dongle_dump.exe and dongle_test.exe that I built from your source file.
both of files cannot detect r4nd dongle.

**Comment by Xyl2k** [comment]
what message do you get from the exes, just 'Dongle not found' ?
this i weird as it use the correct API from rockeydll, see line 501 RY_FIND https://github.com/Xyl2k/DongleMe/blob/master/DongleDump/dongleDump.asm#L501 this should work for every dongle.

**Comment by Xyl2k** [comment]
sorry for intempestive closes, i'm missclicking
could you eventually fire a debugger and trace the problem? it should be easy as it's coded in asm.

**Comment by Ali-Mohebbi** [comment]
I Found the problem.
your rockey4nd.dll file is ver 1.3 and it is old version that not working on windows 10.
I replaced it with Ver 1.4 and everything is ok

**Comment by Ali-Mohebbi** [comment]
I have another question.
inside of emulator directory there is Reg key Act_ANYPC_5F0E5CA0_.reg that contains Signature hex value.
is this Signature unique for all dongles or each dongle has own signature.
how I can acquire signature of my dongle.

**Comment by Xyl2k** [comment]
oh okay, glad you solved it, cd the dll i have is the one from the cd, it might be old. yes the signature in he is unique. may only the challenge guide you.

**Comment by Ali-Mohebbi** [comment]
would you please guid me about the general procedure to generate signature.

**Comment by Ali-Mohebbi** [comment]
Would you please share attached files with me to generate my own emulator.
![image](https://user-images.githubusercontent.com/87544518/198831324-62e1b51a-b8a5-4239-afac-e0223b52c10b.png)

**Comment by Xyl2k** [comment]
Closing the issue as the code problem is solved (well wasn't really a 'code bug' but just an outdated dll from Feitian.)
If you find another bug feel free to reopen an issue again.
