### ISSUE TITLE
Source code for the emulator?

### ISSUE THREAD

**Issue by Anonymous941** [Xyl2k/DongleMe#3]
I'm trying to make a Linux ROCKEY 4 emulator and I have no idea how `RY_SEED` works, and lack a physical dongle.  I have found public documentation, but it just says it uses it uses a "proprietary algorithm"

Because this happens on the dongle itself, I can't reverse engineer any binaries from the SDK.  The emulator provided doesn't have any source code while other parts do, is that intentional?  I'd prefer not to have to decompile it if I don't have to

**Comment by Xyl2k** [comment]
It is, the emulator code isn't public sorry.
And i have no idea about how to do that in linux,
On windows you could have a look on vusbbus source code by Chingachguk and Denger2k for the usb driver part, and then have a look on a dongle for the rest. But once again this is windows driver stuff.
I'm not aware of any emulator of rockey for linux so if you do it i think it would be a first!
I don't really know either a practical usage of RY_SEED either. I guess most of people use it to generate later randomness.. but i haven't encountered it..
The only software that i know who use rockey4nd is X-Ways Forensics, and that this one who picked my interest and pushed me to contact Feitian to buy dongles samples of rockey4nd and their sdk.

**Comment by Xyl2k** [comment]
As first step I would advise you to contact Feitian to acquire a sample box of rockey4nd and do your own experiment with their technology.
That what this repository is about as they don't provide 'demo emulator' to play with tools.
This repository allow you to play with their sdk and test their tools like the 'envelopper' without having the physical dongle.

**Comment by Anonymous941** [comment]
> As first step I would advise you to contact Feitian to acquire a sample box of rockey4nd and do your own experiment with their technology.

Good idea, I'm going to order a demo dongle soon.  The `RY_SEED` implementation is mostly for fun, and so it doesn't break for software that uses it.  I'm thinking I'll try to dump the firmware of the demo dongle and disassemble it

> I'm not aware of any emulator of rockey for linux so if you do it i think it would be a first!

Yeah, I wasn't able to find one either (in fact, this is the only emulator I could find for any platform).  Mine has been working great so far, I just had to create a character device and handle the `ioctl` calls, plus I can set the `USB_DEVFS_PATH` so I don't have to use `/dev/bus/usb`.  Later versions of the SDK use `/dev/rockey`, which is even easier.  I'll make it open source once I'm done

Thanks for your help and for making this repo public!

**Comment by Anonymous941** [comment]
Also, in case it helps, I found many legal and free newer SDK downloads:

https://www.rockey.com.my/portfolio-items/rockey4nd/
https://products.epass.nl/support/rockey-download.html
https://www.rockey.nl/downloads.html
