### ISSUE TITLE
Do you have any solutions for recovering lost passwords?

### ISSUE THREAD

**Issue by holao09** [Xyl2k/DongleMe#4]
I have an old ROCKEY4ND but have lost the password. Can you help me recover it?

**Comment by greenozon** [comment]
if your SW is not packed/protected - try to use your favorite debugger and look for the API that opens up the dongle
there should be vars having values for passwords

**Comment by holao09** [comment]
Can we extract it from the Wireshark USB log?
The software often protects against reverse engineering. It may be hard to extract.

**Comment by greenozon** [comment]
well, maybe
did you give it a try already?

Ideally, if you have a test dongle for which you know P1/P2 you could sniff the traffic and say for sure

**Comment by holao09** [comment]
But I don't know the pattern to detect. The data sent and received between the PC and the dongle is too much. I need some suggestions from you.

**Comment by greenozon** [comment]
I'm not the wireshare/usbtrace guy
I debug stuff in the debugger and thus figure out the info...

**Comment by Xyl2k** [comment]
depend, sometime it's easier to analyse the usb traffic rather than debuging an heavilly protected exe.

**Comment by holao09** [comment]
> depend, sometime it's easier to analyse the usb traffic rather than debuging an heavilly protected exe.

Can you help me by capture the data send to the dongle , which contain P1 and P2 codes? 
Because you know your P1, P2. You can help me get the pattern.

**Comment by Xyl2k** [comment]
not sure on how to do that with wireshark but here are my notes for Sysnucleus USBTrace
Filter on:
 Status: Success
 Direction: Out
 Data: With Data
 Request: CLASS_INTERFACE
 Check "Use Filter" and OK.
Check the device box of USB Feitian
Start sniffing

Launch your app and locate the "(GetReport) CLASS_INTERFACE"
The basic1 and basic2 passwords are there...
```
+--+-----------+-----+-----+-----------+--------+
 01 DF DF DF DF 94 E6 AB 6B DF DF DF DF 00 00 00
+--+-----------+-----+-----+-----------+--------+
   ! Padding   !Basic!Basic! Padding   !        !
   !           !PWD1 !PWD2 !           !        !
+--+-----------+-----+-----+-----------+--------+  
    00 00 00 00 48 39 4b bb
    37 37 37 37 7c 06 43 83
    F8 F8 F8 F8 3B C1 8C 4C
    50 50 50 50 1b 69 24 e4
    51 51 51 51 1a 68 25 65
    5f 5f 5f 5f 14 66 2b eb
```

padding is random 0x00 to 0xFF, passwords are calculated.
my access keys for the dongle are therefore:
Basic PW1: 4839
Basic PW2: 4BBB

Funny to see that during the sniff, the padding was 00 at one point, so with the keys in clear text.

**Comment by holao09** [comment]
I have figured out the formula .


<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/vietn/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/vietn/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


01 | Padding | Padding | Padding | Padding | P1 | P1 | P2 | P2 | Padding |   | P1 XOR Padding | P1 XOR Padding | P2 XOR Padding | P2 XOR Padding
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
01 | EA | EA | EA | EA | 66 | 05 | 99 | 65 | EA |   | 8C | EF | 73 | 8F
01 | EA | EA | EA | EA | 66 | 05 | 99 | 65 | EA |   | 8C | EF | 73 | 8F
01 | 1E | 1E | 1E | 1E | 92 | F1 | 6D | 91 | 1E |   | 8C | EF | 73 | 8F
01 | 4B | 4B | 4B | 4B | C7 | A4 | 38 | C4 | 4B |   | 8C | EF | 73 | 8F
01 | 4B | 4B | 4B | 4B | C7 | A4 | 38 | C4 | 4B |   | 8C | EF | 73 | 8F
01 | 4B | 4B | 4B | 4B | C7 | A4 | 38 | C4 | 4B |   | 8C | EF | 73 | 8F
01 | 28 | 28 | 28 | 28 | A4 | C7 | 5B | A7 | 28 |   | 8C | EF | 73 | 8F
01 | 28 | 28 | 28 | 28 | A4 | C7 | 5B | A7 | 28 |   | 8C | EF | 73 | 8F
01 | 59 | 59 | 59 | 59 | D5 | B6 | 2A | D6 | 59 |   | 8C | EF | 73 | 8F
01 | 54 | 54 | 54 | 54 | D8 | BB | 27 | DB | 54 |   | 8C | EF | 73 | 8F
01 | 54 | 54 | 54 | 54 | D8 | BB | 27 | DB | 54 |   | 8C | EF | 73 | 8F
01 | 54 | 54 | 54 | 54 | D8 | BB | 27 | DB | 54 |   | 8C | EF | 73 | 8F
01 | F9 | F9 | F9 | F9 | 75 | 16 | 8A | 76 | F9 |   | 8C | EF | 73 | 8F
01 | 2A | 2A | 2A | 2A | A6 | C5 | 59 | A5 | 2A |   | 8C | EF | 73 | 8F
01 | 2A | 2A | 2A | 2A | A6 | C5 | 59 | A5 | 2A |   | 8C | EF | 73 | 8F
01 | 8B | 8B | 8B | 8B | 07 | 64 | F8 | 04 | 8B |   | 8C | EF | 73 | 8F
01 | 8B | 8B | 8B | 8B | 07 | 64 | F8 | 04 | 8B |   | 8C | EF | 73 | 8F
01 | 8B | 8B | 8B | 8B | 07 | 64 | F8 | 04 | 8B |   | 8C | EF | 73 | 8F
01 | 3C | 3C | 3C | 3C | B0 | D3 | 4F | B3 | 3C |   | 8C | EF | 73 | 8F
01 | 3C | 3C | 3C | 3C | B0 | D3 | 4F | B3 | 3C |   | 8C | EF | 73 | 8F
01 | 70 | 70 | 70 | 70 | FC | 9F | 03 | FF | 70 |   | 8C | EF | 73 | 8F
01 | 9D | 9D | 9D | 9D | 11 | 72 | EE | 12 | 9D |   | 8C | EF | 73 | 8F
01 | 9D | 9D | 9D | 9D | 11 | 72 | EE | 12 | 9D |   | 8C | EF | 73 | 8F
01 | D1 | D1 | D1 | D1 | 5D | 3E | A2 | 5E | D1 |   | 8C | EF | 73 | 8F
01 | 0A | 0A | 0A | 0A | 86 | E5 | 79 | 85 | 0A |   | 8C | EF | 73 | 8F
01 | 0A | 0A | 0A | 0A | 86 | E5 | 79 | 85 | 0A |   | 8C | EF | 73 | 8F



</body>

</html>
Everything will be come to password.
And. Yes. My password is 8CEF 738F
